mutagen/id3/_specs.py
pyyaml's yaml.dump() failed because it apparently compares instances of ID3TimeStamp with None and empty tuples
```
f = mutagen.File(path)
yaml.dump({'file': f})
```
=> id3.ID3TimeStamp comparator: check type

docs/man/mid3cp.rst, man/mid3cp.1, mutagen/_tools/mid3cp.py, tests/test_tools_mid3cp.py
Instead of replacing the whole tag this will copy over
frames and potentially replace existing frames.
The id3 version of the target will be used. Excluded frames and
frames not supported by the target version will not be copied.
In case the target has no ID3 tag this option has no effect.
=> mid3cp: add --merge option. Fixes #277

mutagen/aiff.py
Minor changes based on lessons learned from #321 (used AIFF as base to implement RIFF/WAVE)
- Fixed range check of chunk-id check 
- Moved duplicate code in `assert_valid_chunk_id(id)`
=> Minor changes in AIFF functionality

mutagen/apev2.py, tests/test_apev2.py
I am using Unison as a backup tool for my music files and every time I update my library's tags with Mutagen some of them are found modified although the audio part and the tags had not been modified. I found out that APEV2 tags are sorted by lengths before saving to file but this is not sufficient. Tags that have the exact same length are saved in random orders because of Python's dictionary implementation. This patch aims to correct this because it adds tags keys to the comparing function and since tag's keys are unique, this ensures that each sorting key is unique too.
The problem is that this is very difficult to test because of its randomness :(
=> Be deterministic when saving to file

mutagen/mp4/__init__.py, tests/test_mp4.py
Typo which made it fall through to the next case.
=> mp4: fix 8bit ints getting saved as 16bit (rtng, stik, shwm). Fixes #349

mutagen/_vorbis.py
Add some more information when _vorbis validate() throws an exception.  I added this working on some new code for whipper.
=> More useful error reporting from validate().

mutagen/id3/_frames.py, tests/test__id3frames.py
This PR adds _pprint() to SYLT class so it doesn't print `[unrepresentable data]` anymore. It also changes __str__ method so that it includes timestamps as well as texts:
```
[1ms]: foo
[16ms]: bar
```
=> pretty print for SYLT

mutagen/id3/_file.py
By letting sphinx/autodoc autogenerate it.
(Adding it manually to the signature would make the line too long.)
=> docs/id3: Add load_v1 option to load() signature

mutagen/_file.py, mutagen/_tags.py, mutagen/aiff.py, mutagen/apev2.py, mutagen/asf/__init__.py, mutagen/dsf.py, mutagen/easyid3.py, mutagen/flac.py, mutagen/id3/_file.py, mutagen/mp4/__init__.py, mutagen/ogg.py
While the decorator make sure that we never get None there, the signature gets
used for API introspection, e.g. pylint. Just add None to all methods where the
decorator allows None in some cases.
=> Add None default values to all filething args for save/delete(). Fixes #363

mutagen/_senf/_argv.py, mutagen/_senf/_environ.py, mutagen/apev2.py
With Python 3.7, I got the following warnings.
```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```
This is a pull request to fix the issue. I tested with 3.7.2 and 2.7.15 and confirmed all the tests passed.
=> Fix collections ABCs deprecation warning

mutagen/mp3/__init__.py
I have absolutely no idea about the meaning of the number, but I have an mp3 file which can only be read if max_syncs >= 1002. The file can be played by many players.
=> increase max_syncs to 1024

mutagen/flac.py, tests/test_flac.py
While the flac spec states that "There may be only one VORBIS_COMMENT block in a stream"
metaflac and other programs don't fail when they parse such a file and just use the first
block (same for VLC and Totem).
Instead of raising when loading a file with multiple blocks just use the first one for the
tags interface and leave the other blocks as is, including writing it back as is.
The only other change is in delete() where we delete all VORBIS_COMMENT blocks, even the
ones not exposed. This makes sure that reloading a file that had its tags deleted doesn't
exposed the other tag block suddenly.
Fixes #377
=> flac: support files with multiple VORBIS_COMMENT blocks. Fixes #377

mutagen/_compat.py, mutagen/id3/_tags.py, tests/test_id3.py
Be a bit stricter in what we allow to end up in the final timestamp
and handle multiple sets of TYER/TDAT/TIME correctly.
=> Rework TYER/TDAT/TIME upgrade to TDRC. Fixes #380

mutagen/mp4/__init__.py, tests/test_mp4.py
The atom is named "hdvd", it's an 8 bit integer where:
0 - SD
1 - 720p
2 - 1080p
iTunes and Apple TV refer to it rather than actual resolution info from the video stream, so it's a helpful tag to have.
=> MP4: Add support for iTunes HD Video tag

mutagen/aiff.py, tests/test_aiff.py
This is consistent with other formats. Keep sample_size as an undocumented field for backward compatibility with existing code.
Fixes #402
=> aiff: renamed sample_size to bits_per_sample

mutagen/aiff.py, tests/test_aiff.py
This refactors the AIFF code to:
- Fix handling of padding bytes: For chunks with odd data size there must be a padding byte added. This is now consistently handled for all chunk manipulation (resize, insert, delete). Previously this was not handled for all cases, and reading a file which had a ID3 chunk with padding could lead to file corruption since mutagen would write this chunk back with an even size but keep the padding byte.
- The code can now safely support multiple chunk insert / resize / delete operations while keeping the in-memory representation of all offsets and sizes intact. Previously it was not safe to e.g. both insert and delete chunks in a loaded file, since the in-memory stored offsets for chunks were not updated. This lead to file corruption since data was manipulated …
=> AIFF: Fix handling of padding bytes, safe chunk manipulation

mutagen/aiff.py
While writing 46147db and ea726fb, I forgot to actually remove the line causing the division by zero, sorry about that :/
=> Fix, for real, a ZeroDivisonError in aiff processing

mutagen/asf/_objects.py
- Guard against an infinite loop
- Wrap a call into a try...catch, since there
are a lot of manual offset fiddling involving
struct.unpack in the child functions, resulting
in a lot of different ways to trigger
a struct.error
=> Improve a bit the robustness of asf parsing

mutagen/aiff.py, tests/test_aiff.py
* raise overflow in case of inf/nan
* handle overflow in parsing code
* raise on negative sample rate
Fixes #455
=> aiff: handle overflow in read_float()

mutagen/_iff.py, mutagen/_riff.py, mutagen/aiff.py, mutagen/wave.py, tests/test_aiff.py
Update the AIFF and RIFF implementations to use common IFF base classes. Both the AIFF and RIFF implementations share a lot of code. The differences between both implementations is that one uses big endian and the other little endian, also they obviously use different types of chunks.
The background for this is that I am also working on a DSDIFF (aka DFF) implementation. DSDIFF is also IFF based and thus again shares most of the code of the AIFF / RIFF implementations. The main difference to AIFF is that DSDIFF uses 8 bytes for the length instead of 4.
So I'm submitting this refactoring first and later the DSDIFF changes on top of this.
=> Extract common IFF code to separate module.

docs/user/examples/fileobj-iface.py, mutagen/_util.py, tests/test__util.py
It has some problems with Windows file shares where it takes 20x the time
of the fallback implementation and has a similar problem with ZFS on Linux,
see #478.
I've done some basic benchmarks with adding extra padding to 30 flac files each around
20-40MB and there is basically no difference.
So just remove mmap.
Fixes #478
=> Don't use mmap for rewriting files

.github/workflows/test.yml, README.rst, setup.py
We now require 3.6+.
The main motivation for this change is improved
type annotation support, see #486
=> Drop support for Python 3.5

mutagen/flac.py
I recently bought some FLAC files from Warp's Bleep store and was surprised to discover that mutagen crashes as follows when processing them (snaffleid3 is a script I wrote):
```
Traceback (most recent call last):                                      
File "/usr/bin/snaffleid3", line 54, in <module>                           
f = FLAC(flac.rstrip("\n"))                                             
File "/usr/lib/python2.7/dist-packages/mutagen/_file.py", line 49, in __init__
self.load(*args, **kwargs)                                                                                      
File "/usr/lib/python2.7/dist-packages/mutagen/_util.py", line 169, in wrapper                    
return func(*args, **kwargs)                                        
File …
```
=> flac: handle files where the first metadata block is not STREAMINFO

mutagen/easyid3.py
According to the specification,
> The 'Content group description' frame [TIT1] is used if the sound belongs to a larger category of sounds/music. For example, classical music is often sorted in different musical sections (e.g. "Piano Concerto", "Weather - Hurricane"). 
which seems like the same thing as ‘grouping’.
=> Map easyid3 grouping to TIT1

mutagen/_tools/mutagen_inspect.py
Small PR to update the `mutagen-inspect` usage help text from:
```bash
$ mutagen-inspect --help
Usage: mutagen-inspect [options]
Options:
-h, --help           show this help message and exit
--no-flac=NO_FLAC    Compatibility; does nothing.
--no-mp3=NO_MP3      Compatibility; does nothing.
--no-apev2=NO_APEV2  Compatibility; does nothing.
```
to:
```bash
$ mutagen-inspect --help
Usage: mutagen-inspect [options] FILE [FILE...]
Options:
-h, --help           show this help message and exit
--no-flac=NO_FLAC    Compatibility; does nothing.
--no-mp3=NO_MP3      Compatibility; does nothing.
--no-apev2=NO_APEV2  Compatibility; does nothing.
```
=> Add usage documentation for mutagen-inspect

mutagen/flac.py, mutagen/ogg.py
There are small typos in:
- mutagen/flac.py
- mutagen/ogg.py
Fixes:
- Should read `occurring` rather than `occuring`.
- Should read `implementation` rather than `implementaton`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

mutagen/wave.py, tests/test_wave.py
Calculated bitrate for WAVE files did not match correct value (as shown in foobar2000 or calculated manually)
Should be: num channels * bits per sample * sample rate
Tests for WAVE were checking incorrect values for bitrate. Redbook audio (stereo, 16bit, 44100Hz) for example should have a bitrate of 1411200 bits per second.
=> Wav bitrate fix

mutagen/flac.py
Hi,
This pull request is a fix to a potential bug about wrong order of function arguments at `mutagen/flac.py`. Please check the changes.
When calling `super`, the first argument should be the class name (see [this](https://stackoverflow.com/questions/8972866/correct-way-to-use-super-argument-passing)).
Best,
Jingxuan
=> Fix a bug about wrong order of function arguments

.github/workflows/test.yml, pyproject.toml, setup.py
Also remove the trove classifiers for specific Python versions.
Not sure if there is any point in maintinging that list given
it's already in the metadata.
=> CI: test with Python 3.10

mutagen/_util.py
256KB was chosen as good enough when doing local copies, but in #553
it was pointed out that this is quite slow with remote filesystems like
NFS etc.
Bump to 1MB to improve that a bit..
=> Bump the buffer size a bit for resizing files

setup.py
Removed python 4 requirements as it doesn't exist and won't be released in near future. So, we don't have to check if the version is lesser than version 4. greater than version 3.7 is enough.
=> Removed python 4 requirement as it does't exist

docs/conf.py
The caption must contain `%s` exactly once¹ and because it did not building the docs using sphinx 6.0 failed.
```
mutagen> reading sources... [ 62%] changelog0mmm00m
mutagen> Exception occurred:
mutagen>   File "/nix/store/45b9bmcr6w6k05syyflc4r8j4gzzbjkm-python3.10-sphinx-6.0.0/lib/python3.10/site-packages/sphinx/ext/extlinks.py", line 101, in role
mutagen>     title = caption % part
mutagen> TypeError: not all arguments converted during string formatting
mutagen> The full traceback has been saved in /build/sphinx-err-kzqq6ki_.log, if you want to report the issue to the developers.
```
[1] https://www.sphinx-doc.org/en/master/usage/extensions/extlinks.html#confval-extlinks
=> docs: Make extlinks compatible with sphinx 6.0

mutagen/wave.py
Microsoft defines these fields as WORD, which is usually unsigned. The audio format byte can take values like FFFE for extensible WAVE, which only makes sense if read unsigned.
Fixes #595
=> Read the WAVE info attributes as unsigned short

fuzzing/fuzztools.py
- Remove unnecessary imports in the fuzzer: the less imported code, the better/faster the fuzzer.
- Put the BytesIO(data) call outside of the loop.
- Use return instead of pass, to exit early and make the fuzzer faster.
- Fix a typo: ccheck → check
- Use a comprehension list instead of loop, since those are significantly faster.
=> Improve a bit the fuzzer

mutagen/id3/_tags.py, tests/test_id3.py
This is an alternative implementation to #529. It allows using `TYER` in non-standard `YYYY-mm-dd` format when upgrading ID3 v2.3 to v2.4. The difference to #529 is that this patch adds tests and also considers the `mm-dd` part in case there is no corresponding `TDAT` frame. This reduces data loss even further in case of non-standard use of `TYER`.
=> Allows TYER tags in the form of 'yyyy-mm-dd'

mutagen/flac.py
I meet the problem when I'm trying to create a Cuesheet block for FLAC and save. When I directly specify `tags.cuesheet = XXX`, the cuesheet tag won't be saved unless I manually add the cuesheet object also to the `metadata_blocks`. This PR changes this behavior so that the cuesheet block will always be saved.
This PR also fix the problem when the ISRC value for a cuesheet track is empty (`None`)
=> Fix cuesheet and seektable saving in FLAC

mutagen/id3/_tags.py, tests/test_id3.py
The extended header size is an integer, so can be negative. This leads to read_full() getting called with a negative size and failing with ValueError.
Handle this case explicitly and raise a proper mutagen exception instead.
=> id3: handle negative extended header sizes

mutagen/id3/_frames.py
Hi
There is a bug in which strings containing subscripted numbers will return True to str.isdigit, so then it tries to cast to int, which raises ValueError. The intended behavior would be closer to str.isdecimal, which will always be safe to cast, see:
```
>>> value = "⁶⁶⁶"
>>> value.isdigit()
True
>>> int(value)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '⁶⁶⁶'
>>> value.isdecimal()
False
```
=> id3 frames fix bad cast due to str.isdigit

mutagen/tak.py, tests/test_tak.py
in case there is just an end block we would succeed with parsing but things would be in a half initalized state, for example failing when pprint() is called.
Make sure we find and parse a stream info block
=> tak: raise in case there is no stream info block

mutagen/ac3.py, tests/test_ac3.py
This would raise AttributeError when parsing the file. Fix the typo bit() -> bits()
=> ac3: fix calls to nonexisting methods

mutagen/apev2.py
The parsing code was depending on __setitem__ checking if the key was valid and raising KeyError, but we only want MutagenError during parsing.
Call is_valid_apev2_key() explicitely and raise APEBadItemError instead.
=> apev2: don't raise KeyError when parsing an invalid key

mutagen/_file.py, mutagen/_iff.py, mutagen/_tags.py, mutagen/_util.py, mutagen/_vorbis.py, mutagen/asf/_util.py, mutagen/id3/_util.py, mutagen/ogg.py, mutagen/smf.py
randomly add them where it was easy and didn't require code changes.
=> Add some type annotations

NEWS
@lazka I put this up here for discussion of whether to do a fresh release soon. I think we have gathered quite some changes and fixes that are worth getting released. One of my motivations is, that I would like to include especially the changes for #596 in the next Picard release. If possible I'd like to do this with a new mutagen release, but I would otherwise just patch the binary releases we do to contain this fix.
Also after a new mutagen release we could reconsider merging #611 . What do you think?
=> Prepare next release

.github/workflows/test.yml, .mypy.ini, README.rst, pyproject.toml, setup.py
=> Drop support for Python 3.7

mutagen/mp3/_util.py, tests/test_mp3.py
See https://issues.oss-fuzz.com/issues/42523736
We could raise there, but we are already returning "?" for unknown flags down below, so just do the same here.
=> mp3: don't fail on non-ascii lame header version flags

mutagen/flac.py
- fixed minor typo in Flac `Picture` class docstring
=> Fix typo in code example for `Picture` in `flac.py`

mutagen/id3/_tags.py
At the time of writing, Mutagen reorders APIC frames upon save without the user being able to influence the order, which causes issues with many players (including iTunes – which is Mutagen’s main compatibility target for MP4 files, though I’m not sure whether it is for ID3 tags) as discussed in issue #436. This implements the closest to a consensus reached in #436: APIC frames are stored last, and not reordered.
This pull request conflicts with #539, as both modify the ID3 `sort_key` function – so allow me to provide a merged version of that as well:
```python
def sort_key(items):
i, (frame, data) = items
if frame.FrameID == "APIC":
secondary_key = i
frame_key = frame.HashKey
elif frame.FrameID == "CHAP":
secondary_key = frame.start_time
frame_key = frame.FrameID
else:
secondary_key = …
```
=> Preserve order of `APIC` frames relative to each other when saving.

.github/workflows/test.yml, pyproject.toml
=> Some CI cleanup/updates; test with Python 3.14

docs/api/id3_frames.rst, mutagen/id3/_frames.py
Currently, Mutagen ever so slightly mangles files that contain multiple `APIC`s with the same description: It appends spaces to the descriptions to make them unique.
https://github.com/quodlibet/mutagen/blob/62a7b3ee9f9c05321a80ba7914226189c66f28c7/mutagen/id3/_frames.py#L1277-L1279
This means that at the time of writing, it’s impossible to tag files with images with the same description using Mutagen. To allow this, this pull request adds a `salt` attribute to the `APIC` frame
This should, as far as I know, be entirely backward-compatible, as the `HashKey` doesn't change.
---
Since I was updating the documentation of `APIC`, I also took the liberty of removing the line “Mutagen will automatically compress large images when saving tags.”, since this appears to no longer be the case: …
=> Add `salt` attribute to `APIC` frames to avoid mangling descriptions and to allow identical descriptions
