- .appveyor.yml
- .travis.yml
- NEWS
- run_wine.sh
- tests/test___init__.py
Use for making the file objects randomly fail instead of doing an exhaustive
test over all operations. Speeds things up a bit.
> tests: use hypothesis

- mutagen/_util.py
- tests/test__util.py
Resolves https://github.com/quodlibet/mutagen/issues/337
> Support __fspath__ for file system paths (PEP 519)

- mutagen/oggvorbis.py
- mutagen/wavpack.py
Just a few small API doc fixes.
> Minor API doc fixes

- mutagen/mp3/__init__.py
- mutagen/wavpack.py
Again very minor fixes to the API docs
> docs: fixed some API attribute descriptions not being shown

- mutagen/ogg.py
> Fix small typo: occured -> occurred

- mutagen/mp4/__init__.py
This should close #416 and #424
> Fix some infinite loops in the mp4 parser

- mutagen/flac.py
> Fix #427: Add __getnewargs__ method to SeekPoint to support pickling

- mutagen/aiff.py
> Fix a division by zero in aiff

- mutagen/asf/_objects.py
> Catch a MemoryError in asf processing

- mutagen/oggtheora.py
> Fix a division by zero in offtheora handling

- fuzzing/.gitignore
- fuzzing/README.rst
- fuzzing/check_crashes.sh
- fuzzing/fuzztools.py
- fuzzing/poetry.lock
- fuzzing/pyproject.toml
- fuzzing/run.sh
- fuzzing/sut.py
- setup.py
> Basic fuzzing integration with python-afl

- mutagen/ogg.py
Sorry this is such a minor PR. Love the project!
> Minor typo in comments

- mutagen/_util.py
- tests/test__util.py
> Add pickle support for enum types

- mutagen/_util.py
From 64kb to 256kb. This makes things a bit faster on my machine.
Increasing it even more doesn't change much here.
See #478
> Increase the buffer for rewriting files a bit

- .github/workflows/test.yml
- .mypy.ini
- README.rst
- pyproject.toml
- setup.py
> Drop support for Python 3.6

- mutagen/_iff.py
Some AIFF / WAVE files have smaller actual file size then the reported size of their chunks, as trailing null bytes are sometimes truncated.
This is alternative implementation of https://github.com/quodlibet/mutagen/pull/515 which makes sure inserting or resizing chunk operations operate inside the actual file size limits.
Fixes #496
See also discussion at https://community.metabrainz.org/t/receiving-valueerror-when-saving-some-files/502884/2
> Handle truncated IFF files

- mutagen/mp4/__init__.py
> Add a check for wrong offsets in mp4 files

- .github/workflows/test.yml
- pyproject.toml
* 3.8 is no longer supported
* mypy seems to install fine now with it, but is way too slow
> CI: Update to PyPy 3.9

- docs/dev/id3.rst
- docs/dev/index.rst
- docs/index.rst
where we can collection links to specs, note spec deviations etc.
> docs: start a developer guide

- .github/workflows/test.yml
> CI: test with Python 3.13
